name: Export Drawio Diagrams

on:
  push:
    paths:
      - 'files/**/*.drawio'
  pull_request:
    paths:
      - 'files/**/*.drawio'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  export-diagrams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref }}
          fetch-depth: 0

      - name: Export Draw.io diagrams to PNG
        uses: rlespinasse/drawio-export-action@v2
        with:
          path: files
          format: png
          transparent: false
          
      - name: Fix file permissions
        run: sudo chown -R $USER:$USER files/
          
      - name: Commit directly to branch
        if: github.ref != 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'files/**/*.png'
          commit_message: Update diagrams

      - name: Create Pull Request
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update diagrams
          branch: update-diagrams-bot
          title: Update exported drawio diagrams
          body: Automated PR to update diagrams from modified .drawio files.
          add-paths: 'files/**/*.png'
